name: Node.js CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x, 16.x, 18.x]  

    steps:
    - uses: actions/checkout@v3

    - name: Set up Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'

    - name: Install server dependencies
      working-directory: ./w8d4/CIJournal/server
      run: npm ci

    - name: Build server
      working-directory: ./w8d4/CIJournal/server
      run: npm run build --if-present

    - name: Install client dependencies
      working-directory: ./w8d4/CIJournal/client
      run: npm ci

    - name: Build client
      working-directory: ./w8d4/CIJournal/client
      run: npm run build --if-present

    - name: Test server
      working-directory: ./w8d4/CIJournal/server
      run: npm test --if-present

    - name: Test client
      working-directory: ./w8d4/CIJournal/client
      run: npm test --if-present
