name: Node.js CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x]  # Ensure this version matches your project's requirements

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
        cache-dependency-path: w8d4/CIJournal/server/package-lock.json

    - name: Cache Server Node Modules
      uses: actions/cache@v2
      with:
        path: w8d4/CIJournal/server/node_modules
        key: server-${{ matrix.node-version }}-${{ hashFiles('w8d4/CIJournal/server/package-lock.json') }}
        restore-keys: |
          server-${{ matrix.node-version }}-

    - name: Install Server Dependencies
      working-directory: ./w8d4/CIJournal/server
      run: npm install

    - name: Cache Client Node Modules
      uses: actions/cache@v2
      with:
        path: w8d4/CIJournal/client/node_modules
        key: client-${{ matrix.node-version }}-${{ hashFiles('w8d4/CIJournal/client/package-lock.json') }}
        restore-keys: |
          client-${{ matrix.node-version }}-

    - name: Install Client Dependencies
      working-directory: ./w8d4/CIJournal/client
      run: npm install
